
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 robot.gltf 
Author: solodovnykov (https://sketchfab.com/solodovnykov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sachiel-evangelion-3c212c7ce6ac4284a8b718078bc6fc0f
Title: Sachiel - Evangelion
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';


export default function Robot(props) {
  const { nodes, materials } = useGLTF('/robot.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0.003, 188.229, 84.445]} scale={100}>
          <mesh geometry={nodes.Body_low_Body_2_0.geometry} material={materials.Body_2} />
          <mesh geometry={nodes.Body_low_Body_5_0.geometry} material={materials.Body_5} />
          <mesh geometry={nodes.Body_low_Body_4_0.geometry} material={materials.Body_4} />
          <mesh geometry={nodes.Body_low_Body_3_0.geometry} material={materials.Body_3} />
          <mesh geometry={nodes.Body_low_Body_6_0.geometry} material={materials.Body_6} />
          <mesh geometry={nodes.Body_low_Body_7_0.geometry} material={materials.Body_7} />
          <mesh geometry={nodes.Body_low_Body_1_0.geometry} material={materials.Body_1} />
        </group>
        <group position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.BackBone_low_BackBone_1_0.geometry} material={materials.BackBone_1} />
          <mesh geometry={nodes.BackBone_low_BackBone_2_0.geometry} material={materials.BackBone_2} />
        </group>
        <group position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Shoulders_low_Shoulders_1_0.geometry} material={materials.Shoulders_1} />
          <mesh geometry={nodes.Shoulders_low_Shoulders_2_0.geometry} material={materials.Shoulders_2} />
        </group>
        <group position={[0.003, 188.229, 84.445]} scale={2.729}>
          <mesh geometry={nodes.Eye_Material001_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Eye_Eye_0.geometry} material={materials.material} />
        </group>
        <group position={[-19.297, 232.395, 130.02]} rotation={[-1.537, 0.267, -0.435]} scale={1.954}>
          <mesh geometry={nodes['1'].geometry} material={materials.material} />
          <mesh geometry={nodes['0'].geometry} material={materials['Material.001']} />
        </group>
        <group position={[-24.677, 234.234, 126.34]} rotation={[-1.537, 0.267, -0.557]} scale={1.954}>
          <mesh geometry={nodes['3'].geometry} material={materials.material} />
          <mesh geometry={nodes['2'].geometry} material={materials['Material.001']} />
        </group>
        <mesh geometry={nodes.Mask_low_Mask001_0.geometry} material={materials['Mask.001']} position={[0, 216.492, 155.041]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Leg_Bones_1_low_LegBone1_0.geometry} material={materials.LegBone1} position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Leg_Bones_2_low_LegBone2_0.geometry} material={materials.LegBone2} position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Leg_Bones_3_low_LegBone3_0.geometry} material={materials.LegBone3} position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.ElbowSpikes_low_ElbowSpikes_0.geometry} material={materials.ElbowSpikes} position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Ribs_low_Ribs_0.geometry} material={materials.Ribs} position={[0.003, 188.229, 84.445]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Mask2_low_Mask001_0.geometry} material={materials['Mask.001']} position={[-27.351, 238.209, 137.92]} rotation={[-1.838, 0.487, -0.469]} scale={[73.026, 73.026, 73.027]} />
        <mesh geometry={nodes.Caruncula_1_Material002_0.geometry} material={materials['Material.002']} position={[0, 216.492, 155.041]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Caruncula_2_Material002_0.geometry} material={materials['Material.002']} position={[0, 216.492, 155.041]} rotation={[-Math.PI / 2, 0, 0]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.Caruncula_3_Material002_0.geometry} material={materials['Material.002']} position={[-21.254, 232.4, 130.827]} rotation={[-1.508, 0.203, -0.483]} scale={100} />
        <mesh geometry={nodes.Caruncula_4_Material002_0.geometry} material={materials['Material.002']} position={[-24.662, 233.773, 128.39]} rotation={[-1.383, 0.164, -0.316]} scale={[-100, 100, 100]} />
        <mesh geometry={nodes.Sphere_Sphere_0.geometry} material={materials.Sphere} position={[0, 178.759, 106.309]} rotation={[-0.75, 0, 0]} scale={11.982} />
      </group>
    </group>
  )
}

useGLTF.preload('/robot.gltf')









